CREATE TABLE Users(
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(200) NOT NULL,
    password VARCHAR(500) NOT NULL
    userCreatedAt DATE DEFAULT(CURRENT_TIMESTAMP)
)